name: Build SQM-NFT IPK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          path: 'sqm-src'

      - name: Download OpenWrt SDK
        run: |
          wget -qO sdk.tar.zst "https://downloads.openwrt.org/releases/24.10.0/targets/rockchip/armv8/openwrt-sdk-24.10.0-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          mkdir openwrt-sdk && tar -I zstd -xf sdk.tar.zst -C openwrt-sdk --strip-components=1

      - name: Prepare Package and Build
        run: |
          cd openwrt-sdk
          ./scripts/feeds update -a
          
          mkdir -p package/sqm-scripts-nft
          cp ../sqm-src/openwrt-pkg/Makefile package/sqm-scripts-nft/Makefile
          cp -r ../sqm-src/src package/sqm-scripts-nft/
          cp -r ../sqm-src/platform package/sqm-scripts-nft/
          cp ../sqm-src/Makefile package/sqm-scripts-nft/Makefile.main
          
          make defconfig
          make package/sqm-scripts-nft/compile V=s

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sqm-nft-24.10.0
          path: openwrt-sdk/bin/packages/*/base/*.ipk
