name: Build SQM-NFT (Dual Format)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build for OpenWrt ${{ matrix.owrt_ver }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - owrt_ver: "24.10.0"
            pkg_ext: "ipk"
            sdk_url: "https://downloads.openwrt.org/releases/24.10.0/targets/rockchip/armv8/openwrt-sdk-24.10.0-rockchip-armv8_gcc-13.3.0_musl.Linux-x86_64.tar.zst"
          
          - owrt_ver: "25.12.2"
            pkg_ext: "apk"
            sdk_url: "https://downloads.openwrt.org/releases/25.12.2/targets/rockchip/armv8/openwrt-sdk-25.12.2-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64.tar.zst"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          path: 'sqm-src'

      - name: Patch Makefile version
        run: |
          sed -i "s/^PKG_RELEASE:=.*/PKG_RELEASE:=${{ github.run_number }}/" sqm-src/openwrt-pkg/Makefile

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc wget python3-pyelftools python3-setuptools python3-dev

      - name: Download and Unpack SDK
        run: |
          wget -qO sdk.tar.zst "${{ matrix.sdk_url }}"
          mkdir openwrt-sdk
          tar -I zstd -xf sdk.tar.zst -C openwrt-sdk --strip-components=1

      - name: Prepare Package and Build
        run: |
          cd openwrt-sdk
          
          # Скачиваем списки пакетов и линкуем их (с новыми python-зависимостями ошибка prereq уйдет)
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
          # Копируем структуру твоего проекта
          mkdir -p package/sqm-scripts-nft
          cp ../sqm-src/openwrt-pkg/Makefile package/sqm-scripts-nft/Makefile
          cp -r ../sqm-src/src package/sqm-scripts-nft/
          cp -r ../sqm-src/platform package/sqm-scripts-nft/
          cp ../sqm-src/Makefile package/sqm-scripts-nft/Makefile.main
          
          # Подготавливаем конфиг и собираем конкретно твой пакет
          make defconfig
          make package/sqm-scripts-nft/compile V=s -j$(nproc)

          # Ищем собранный файл
          FILE_PATH=$(find bin/packages/ -name "sqm-scripts-nft*.${{ matrix.pkg_ext }}" | head -n 1)
          
          if [ -z "$FILE_PATH" ]; then
            echo "Error: Failed to find built .${{ matrix.pkg_ext }} file."
            exit 1
          fi
          
          echo "artifact_path=openwrt-sdk/$FILE_PATH" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: sqm-scripts-nft-${{ matrix.owrt_ver }}-rev${{ github.run_number }}
          path: ${{ env.artifact_path }}
          if-no-files-found: error
